# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fender/senscopic_sdk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fender/senscopic_sdk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fender/senscopic_sdk/CMakeFiles /home/fender/senscopic_sdk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fender/senscopic_sdk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named senscopic

# Build rule for target.
senscopic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 senscopic
.PHONY : senscopic

# fast build rule for target.
senscopic/fast:
	$(MAKE) -f CMakeFiles/senscopic.dir/build.make CMakeFiles/senscopic.dir/build
.PHONY : senscopic/fast

#=============================================================================
# Target rules for targets named camtest

# Build rule for target.
camtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 camtest
.PHONY : camtest

# fast build rule for target.
camtest/fast:
	$(MAKE) -f CMakeFiles/camtest.dir/build.make CMakeFiles/camtest.dir/build
.PHONY : camtest/fast

camtest.o: camtest.cpp.o

.PHONY : camtest.o

# target to build an object file
camtest.cpp.o:
	$(MAKE) -f CMakeFiles/camtest.dir/build.make CMakeFiles/camtest.dir/camtest.cpp.o
.PHONY : camtest.cpp.o

camtest.i: camtest.cpp.i

.PHONY : camtest.i

# target to preprocess a source file
camtest.cpp.i:
	$(MAKE) -f CMakeFiles/camtest.dir/build.make CMakeFiles/camtest.dir/camtest.cpp.i
.PHONY : camtest.cpp.i

camtest.s: camtest.cpp.s

.PHONY : camtest.s

# target to generate assembly for a file
camtest.cpp.s:
	$(MAKE) -f CMakeFiles/camtest.dir/build.make CMakeFiles/camtest.dir/camtest.cpp.s
.PHONY : camtest.cpp.s

src/dumpTool.o: src/dumpTool.cpp.o

.PHONY : src/dumpTool.o

# target to build an object file
src/dumpTool.cpp.o:
	$(MAKE) -f CMakeFiles/senscopic.dir/build.make CMakeFiles/senscopic.dir/src/dumpTool.cpp.o
.PHONY : src/dumpTool.cpp.o

src/dumpTool.i: src/dumpTool.cpp.i

.PHONY : src/dumpTool.i

# target to preprocess a source file
src/dumpTool.cpp.i:
	$(MAKE) -f CMakeFiles/senscopic.dir/build.make CMakeFiles/senscopic.dir/src/dumpTool.cpp.i
.PHONY : src/dumpTool.cpp.i

src/dumpTool.s: src/dumpTool.cpp.s

.PHONY : src/dumpTool.s

# target to generate assembly for a file
src/dumpTool.cpp.s:
	$(MAKE) -f CMakeFiles/senscopic.dir/build.make CMakeFiles/senscopic.dir/src/dumpTool.cpp.s
.PHONY : src/dumpTool.cpp.s

src/hid.o: src/hid.c.o

.PHONY : src/hid.o

# target to build an object file
src/hid.c.o:
	$(MAKE) -f CMakeFiles/senscopic.dir/build.make CMakeFiles/senscopic.dir/src/hid.c.o
.PHONY : src/hid.c.o

src/hid.i: src/hid.c.i

.PHONY : src/hid.i

# target to preprocess a source file
src/hid.c.i:
	$(MAKE) -f CMakeFiles/senscopic.dir/build.make CMakeFiles/senscopic.dir/src/hid.c.i
.PHONY : src/hid.c.i

src/hid.s: src/hid.c.s

.PHONY : src/hid.s

# target to generate assembly for a file
src/hid.c.s:
	$(MAKE) -f CMakeFiles/senscopic.dir/build.make CMakeFiles/senscopic.dir/src/hid.c.s
.PHONY : src/hid.c.s

src/uvc_interface.o: src/uvc_interface.cpp.o

.PHONY : src/uvc_interface.o

# target to build an object file
src/uvc_interface.cpp.o:
	$(MAKE) -f CMakeFiles/senscopic.dir/build.make CMakeFiles/senscopic.dir/src/uvc_interface.cpp.o
.PHONY : src/uvc_interface.cpp.o

src/uvc_interface.i: src/uvc_interface.cpp.i

.PHONY : src/uvc_interface.i

# target to preprocess a source file
src/uvc_interface.cpp.i:
	$(MAKE) -f CMakeFiles/senscopic.dir/build.make CMakeFiles/senscopic.dir/src/uvc_interface.cpp.i
.PHONY : src/uvc_interface.cpp.i

src/uvc_interface.s: src/uvc_interface.cpp.s

.PHONY : src/uvc_interface.s

# target to generate assembly for a file
src/uvc_interface.cpp.s:
	$(MAKE) -f CMakeFiles/senscopic.dir/build.make CMakeFiles/senscopic.dir/src/uvc_interface.cpp.s
.PHONY : src/uvc_interface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... senscopic"
	@echo "... edit_cache"
	@echo "... camtest"
	@echo "... camtest.o"
	@echo "... camtest.i"
	@echo "... camtest.s"
	@echo "... src/dumpTool.o"
	@echo "... src/dumpTool.i"
	@echo "... src/dumpTool.s"
	@echo "... src/hid.o"
	@echo "... src/hid.i"
	@echo "... src/hid.s"
	@echo "... src/uvc_interface.o"
	@echo "... src/uvc_interface.i"
	@echo "... src/uvc_interface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

