#ifndef SRC_RECTIFY_INIT_H_
#define SRC_RECTIFY_INIT_H_

#define     RECT_BASE_ADDR      0xb0010000
#define		RECT_MODULE_ENB		0xff00
#define		RECT_MODE		0xff04
#define		RECT_FRAME_MODE		0xff08
#define		RECT_QUEUE_MODE		0xff0c
#define		RECT_LUT_MODE		0xff10
#define		RECT_EQU_MODE		0xff14
#define		RECT_BLOCK_MODE		0xff18
#define		RECT_SLICE_MODE		0xff1c
#define		RECT_BIST		0xff20
#define		RECT_BLOCK_BIST		0xff30
#define		RECT_SLICE_BIST		0xff34
#define		RECT_IMAGE_BUF_NUM	0xff38

#define		RECT_IMAGE_START0	0xff40
#define		RECT_IMAGE_START1	0xff44
#define		RECT_IMAGE_START2	0xff48
#define		RECT_IMAGE_START3	0xff4c
#define		RECT_IMAGE_OFFSET0	0xff50
#define		RECT_IMAGE_OFFSET1	0xff54
#define		RECT_IMAGE_OFFSET2	0xff58
#define		RECT_IMAGE_OFFSET3	0xff5c 
#define		RECT_INT_CONTROL	0xff60 

#define		RECT_WINDOW_START0	0xff80
#define		RECT_WINDOW_START1	0xff84
#define		RECT_WINDOW_START2	0xff88
#define		RECT_WINDOW_START3	0xff8c
#define		RECT_WINDOW_OFFSET0	0xff90
#define		RECT_WINDOW_OFFSET1	0xff94
#define		RECT_WINDOW_OFFSET2	0xff98
#define		RECT_WINDOW_OFFSET3	0xff9c
#define		RECT_FRAME_BLANK	0xffb0

#define		RECT_SOURCE_DEFINE0	0xffc0
#define		RECT_SOURCE_DEFINE1	0xffc4
#define		RECT_SOURCE_DEFINE2	0xffc8
#define		RECT_SOURCE_DEFINE3	0xffcc
#define		RECT_TARGET_DEFINE0	0xffd0
#define		RECT_TARGET_DEFINE1	0xffd4
#define		RECT_TARGET_DEFINE2	0xffd8
#define		RECT_TARGET_DEFINE3	0xffdc
#define		RECT_WINDOW_DEFINE0	0xffe0
#define		RECT_WINDOW_DEFINE1	0xffe4
#define		RECT_WINDOW_DEFINE2	0xffe8
#define		RECT_WINDOW_DEFINE3	0xffec

#define		RECT_LINE_OFFSET01	0xfe00
#define		RECT_LINE_OFFSET23	0xfe04
#define		RECT_SLICE_FRAME	0xfe0c

#define		RECT_SLICE_HOR_BLANK0	0xfe10
#define		RECT_SLICE_HOR_BLANK1	0xfe14
#define		RECT_SLICE_HOR_BLANK2	0xfe18
#define		RECT_SLICE_HOR_BLANK3	0xfe1c
#define		RECT_SLICE_VER_BLANK0	0xfe20
#define		RECT_SLICE_VER_BLANK1	0xfe24
#define		RECT_SLICE_VER_BLANK2	0xfe28
#define		RECT_SLICE_VER_BLANK3	0xfe2c

#define		RECT_LUT_WINDOW_START0	0xfff0
#define		RECT_LUT_WINDOW_START1	0xfff4
#define		RECT_LUT_WINDOW_START2	0xfff8
#define		RECT_LUT_WINDOW_START3	0xfffc

#define		RECT_LUT_IMAGE_WIDTH0	0xfe30
#define		RECT_LUT_IMAGE_WIDTH1	0xfe34
#define		RECT_BLOCK_YUV_FIX	0xfe38
#define		RECT_CHAIN_CONTROL	0xfe3c

#define		RECT_LINE_GROUP0	0xfe40
#define		RECT_LINE_GROUP1	0xfe44
#define		RECT_LINE_GROUP2	0xfe48
#define		RECT_LINE_GROUP3	0xfe4c

#define		RECT_FRAME_COUNT0	0xfe50
#define		RECT_FRAME_COUNT1	0xfe54
#define		RECT_FRAME_COUNT2	0xfe58
#define		RECT_FRAME_COUNT3	0xfe5c
#define		RECT_FRAME_CONTROL	0xfe60
#define		RECT_SLICE_SKIP0	0xfe70
#define		RECT_SLICE_SKIP1	0xfe74
#define		RECT_SLICE_SKIP2	0xfe78
#define		RECT_SLICE_SKIP3	0xfe7c

#define		RECT_LEFT_START_DEFINE_0	0xf000
#define		RECT_LEFT_OFFSET_DEFINE_0	0xf004
#define		RECT_LEFT_HOR_X_INC_0		0xf010
#define		RECT_LEFT_HOR_Y_INC_0		0xf014
#define		RECT_LEFT_HOR_Z_INC_0		0xf018
#define		RECT_LEFT_VER_X_INC_0		0xf01c
#define		RECT_LEFT_VER_Y_INC_0		0xf020
#define		RECT_LEFT_VER_Z_INC_0		0xf024
#define		RECT_LEFT_VER_X_INI_0		0xf028
#define		RECT_LEFT_VER_Y_INI_0		0xf02c
#define		RECT_LEFT_VER_Z_INI_0		0xf030
#define         RECT_LEFT_FISH_K1_0            	0xf034
#define         RECT_LEFT_FISH_K2_0            	0xf038
#define         RECT_LEFT_FISH_K3_0            	0xf03c
#define         RECT_LEFT_FISH_K4_0            	0xf040
#define         RECT_LEFT_STEREO_K1_0           0xf044
#define         RECT_LEFT_STEREO_K2_0           0xf048
#define         RECT_LEFT_STEREO_K3_0           0xf04c
#define         RECT_LEFT_STEREO_P1_0           0xf050
#define         RECT_LEFT_STEREO_P2_0           0xf054
#define         RECT_LEFT_FX_0          	0xf058 
#define         RECT_LEFT_FY_0          	0xf05c
#define         RECT_LEFT_CX_0          	0xf060 
#define         RECT_LEFT_CY_0          	0xf064
#define		RECT_RIGHT_START_DEFINE_0	0xf080
#define		RECT_RIGHT_OFFSET_DEFINE_0	0xf084
#define         RECT_RIGHT_HOR_X_INC_0          0xf090
#define         RECT_RIGHT_HOR_Y_INC_0          0xf094
#define         RECT_RIGHT_HOR_Z_INC_0          0xf098
#define         RECT_RIGHT_VER_X_INC_0          0xf09c
#define         RECT_RIGHT_VER_Y_INC_0          0xf0a0
#define         RECT_RIGHT_VER_Z_INC_0          0xf0a4
#define         RECT_RIGHT_VER_X_INI_0          0xf0a8
#define         RECT_RIGHT_VER_Y_INI_0          0xf0ac
#define         RECT_RIGHT_VER_Z_INI_0          0xf0b0
#define         RECT_RIGHT_FISH_K1_0            0xf0b4
#define         RECT_RIGHT_FISH_K2_0            0xf0b8
#define         RECT_RIGHT_FISH_K3_0            0xf0bc
#define         RECT_RIGHT_FISH_K4_0            0xf0c0
#define         RECT_RIGHT_STEREO_K1_0          0xf0c4
#define         RECT_RIGHT_STEREO_K2_0          0xf0c8
#define         RECT_RIGHT_STEREO_K3_0          0xf0cc
#define         RECT_RIGHT_STEREO_P1_0          0xf0d0
#define         RECT_RIGHT_STEREO_P2_0          0xf0d4
#define         RECT_RIGHT_FX_0          	0xf0d8
#define         RECT_RIGHT_FY_0          	0xf0dc 
#define         RECT_RIGHT_CX_0          	0xf0e0
#define         RECT_RIGHT_CY_0          	0xf0e4 

#define         RECT_LEFT_START_DEFINE_1        0xf100
#define         RECT_LEFT_OFFSET_DEFINE_1       0xf104
#define         RECT_LEFT_HOR_X_INC_1           0xf110
#define         RECT_LEFT_HOR_Y_INC_1           0xf114
#define         RECT_LEFT_HOR_Z_INC_1           0xf118
#define         RECT_LEFT_VER_X_INC_1           0xf11c
#define         RECT_LEFT_VER_Y_INC_1           0xf120
#define         RECT_LEFT_VER_Z_INC_1           0xf124
#define         RECT_LEFT_VER_X_INI_1           0xf128
#define         RECT_LEFT_VER_Y_INI_1           0xf12c
#define         RECT_LEFT_VER_Z_INI_1           0xf130
#define         RECT_LEFT_FISH_K1_1             0xf134
#define         RECT_LEFT_FISH_K2_1             0xf138
#define         RECT_LEFT_FISH_K3_1             0xf13c
#define         RECT_LEFT_FISH_K4_1             0xf140
#define         RECT_LEFT_STEREO_K1_1           0xf144
#define         RECT_LEFT_STEREO_K2_1           0xf148
#define         RECT_LEFT_STEREO_K3_1           0xf14c
#define         RECT_LEFT_STEREO_P1_1           0xf150
#define         RECT_LEFT_STEREO_P2_1           0xf154
#define         RECT_LEFT_FX_1                  0xf158
#define         RECT_LEFT_FY_1                  0xf15c
#define         RECT_LEFT_CX_1                  0xf160
#define         RECT_LEFT_CY_1                  0xf164
#define         RECT_RIGHT_START_DEFINE_1       0xf180
#define         RECT_RIGHT_OFFSET_DEFINE_1      0xf184 
#define         RECT_RIGHT_HOR_X_INC_1          0xf190
#define         RECT_RIGHT_HOR_Y_INC_1          0xf194
#define         RECT_RIGHT_HOR_Z_INC_1          0xf198  
#define         RECT_RIGHT_VER_X_INC_1          0xf19c
#define         RECT_RIGHT_VER_Y_INC_1          0xf1a0  
#define         RECT_RIGHT_VER_Z_INC_1          0xf1a4  
#define         RECT_RIGHT_VER_X_INI_1          0xf1a8  
#define         RECT_RIGHT_VER_Y_INI_1          0xf1ac
#define         RECT_RIGHT_VER_Z_INI_1          0xf1b0
#define         RECT_RIGHT_FISH_K1_1            0xf1b4
#define         RECT_RIGHT_FISH_K2_1            0xf1b8
#define         RECT_RIGHT_FISH_K3_1            0xf1bc
#define         RECT_RIGHT_FISH_K4_1            0xf1c0
#define         RECT_RIGHT_STEREO_K1_1          0xf1c4
#define         RECT_RIGHT_STEREO_K2_1          0xf1c8
#define         RECT_RIGHT_STEREO_K3_1          0xf1cc
#define         RECT_RIGHT_STEREO_P1_1          0xf1d0
#define         RECT_RIGHT_STEREO_P2_1          0xf1d4
#define         RECT_RIGHT_FX_1                 0xf1d8
#define         RECT_RIGHT_FY_1                 0xf1dc
#define         RECT_RIGHT_CX_1                 0xf1e0
#define         RECT_RIGHT_CY_1                 0xf1e4

#define         RECT_LEFT_START_DEFINE_2        0xf200
#define         RECT_LEFT_OFFSET_DEFINE_2       0xf204
#define         RECT_LEFT_HOR_X_INC_2           0xf210
#define         RECT_LEFT_HOR_Y_INC_2           0xf214
#define         RECT_LEFT_HOR_Z_INC_2           0xf218
#define         RECT_LEFT_VER_X_INC_2           0xf21c
#define         RECT_LEFT_VER_Y_INC_2           0xf220
#define         RECT_LEFT_VER_Z_INC_2           0xf224
#define         RECT_LEFT_VER_X_INI_2           0xf228
#define         RECT_LEFT_VER_Y_INI_2           0xf22c
#define         RECT_LEFT_VER_Z_INI_2           0xf230
#define         RECT_LEFT_FISH_K1_2             0xf234
#define         RECT_LEFT_FISH_K2_2             0xf238
#define         RECT_LEFT_FISH_K3_2             0xf23c
#define         RECT_LEFT_FISH_K4_2             0xf240
#define         RECT_LEFT_STEREO_K1_2           0xf244
#define         RECT_LEFT_STEREO_K2_2           0xf248
#define         RECT_LEFT_STEREO_K3_2           0xf24c
#define         RECT_LEFT_STEREO_P1_2           0xf250
#define         RECT_LEFT_STEREO_P2_2           0xf254
#define         RECT_LEFT_FX_2                  0xf258
#define         RECT_LEFT_FY_2                  0xf25c
#define         RECT_LEFT_CX_2                  0xf260
#define         RECT_LEFT_CY_2                  0xf264
#define         RECT_RIGHT_START_DEFINE_2       0xf280
#define         RECT_RIGHT_OFFSET_DEFINE_2      0xf284 
#define         RECT_RIGHT_HOR_X_INC_2          0xf290
#define         RECT_RIGHT_HOR_Y_INC_2          0xf294
#define         RECT_RIGHT_HOR_Z_INC_2          0xf298  
#define         RECT_RIGHT_VER_X_INC_2          0xf29c
#define         RECT_RIGHT_VER_Y_INC_2          0xf2a0  
#define         RECT_RIGHT_VER_Z_INC_2          0xf2a4  
#define         RECT_RIGHT_VER_X_INI_2          0xf2a8  
#define         RECT_RIGHT_VER_Y_INI_2          0xf2ac
#define         RECT_RIGHT_VER_Z_INI_2          0xf2b0
#define         RECT_RIGHT_FISH_K1_2            0xf2b4
#define         RECT_RIGHT_FISH_K2_2            0xf2b8
#define         RECT_RIGHT_FISH_K3_2            0xf2bc
#define         RECT_RIGHT_FISH_K4_2            0xf2c0
#define         RECT_RIGHT_STEREO_K1_2          0xf2c4
#define         RECT_RIGHT_STEREO_K2_2          0xf2c8
#define         RECT_RIGHT_STEREO_K3_2          0xf2cc
#define         RECT_RIGHT_STEREO_P1_2          0xf2d0
#define         RECT_RIGHT_STEREO_P2_2          0xf2d4
#define         RECT_RIGHT_FX_2                 0xf2d8
#define         RECT_RIGHT_FY_2                 0xf2dc
#define         RECT_RIGHT_CX_2                 0xf2e0
#define         RECT_RIGHT_CY_2                 0xf2e4

#define         RECT_LEFT_START_DEFINE_3        0xf300
#define         RECT_LEFT_OFFSET_DEFINE_3       0xf304
#define         RECT_LEFT_HOR_X_INC_3           0xf310
#define         RECT_LEFT_HOR_Y_INC_3           0xf314
#define         RECT_LEFT_HOR_Z_INC_3           0xf318
#define         RECT_LEFT_VER_X_INC_3           0xf31c
#define         RECT_LEFT_VER_Y_INC_3           0xf320
#define         RECT_LEFT_VER_Z_INC_3           0xf324
#define         RECT_LEFT_VER_X_INI_3           0xf328
#define         RECT_LEFT_VER_Y_INI_3           0xf32c
#define         RECT_LEFT_VER_Z_INI_3           0xf330
#define         RECT_LEFT_FISH_K1_3             0xf334
#define         RECT_LEFT_FISH_K2_3             0xf338
#define         RECT_LEFT_FISH_K3_3             0xf33c
#define         RECT_LEFT_FISH_K4_3             0xf340
#define         RECT_LEFT_STEREO_K1_3           0xf344
#define         RECT_LEFT_STEREO_K2_3           0xf348
#define         RECT_LEFT_STEREO_K3_3           0xf34c
#define         RECT_LEFT_STEREO_P1_3           0xf350
#define         RECT_LEFT_STEREO_P2_3           0xf354
#define         RECT_LEFT_FX_3                  0xf358
#define         RECT_LEFT_FY_3                  0xf35c
#define         RECT_LEFT_CX_3                  0xf360
#define         RECT_LEFT_CY_3                  0xf364
#define         RECT_RIGHT_START_DEFINE_3       0xf380
#define         RECT_RIGHT_OFFSET_DEFINE_3      0xf384 
#define         RECT_RIGHT_HOR_X_INC_3          0xf390
#define         RECT_RIGHT_HOR_Y_INC_3          0xf394
#define         RECT_RIGHT_HOR_Z_INC_3          0xf398  
#define         RECT_RIGHT_VER_X_INC_3          0xf39c
#define         RECT_RIGHT_VER_Y_INC_3          0xf3a0  
#define         RECT_RIGHT_VER_Z_INC_3          0xf3a4  
#define         RECT_RIGHT_VER_X_INI_3          0xf3a8  
#define         RECT_RIGHT_VER_Y_INI_3          0xf3ac
#define         RECT_RIGHT_VER_Z_INI_3          0xf3b0
#define         RECT_RIGHT_FISH_K1_3            0xf3b4
#define         RECT_RIGHT_FISH_K2_3            0xf3b8
#define         RECT_RIGHT_FISH_K3_3            0xf3bc
#define         RECT_RIGHT_FISH_K4_3            0xf3c0
#define         RECT_RIGHT_STEREO_K1_3          0xf3c4
#define         RECT_RIGHT_STEREO_K2_3          0xf3c8
#define         RECT_RIGHT_STEREO_K3_3          0xf3cc
#define         RECT_RIGHT_STEREO_P1_3          0xf3d0
#define         RECT_RIGHT_STEREO_P2_3          0xf3d4
#define         RECT_RIGHT_FX_3                 0xf3d8
#define         RECT_RIGHT_FY_3                 0xf3dc
#define         RECT_RIGHT_CX_3                 0xf3e0
#define         RECT_RIGHT_CY_3                 0xf3e4

#endif